services:
  - type: web
    name: zara-bodyelite
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    branch: main
    autoDeploy: true

    envVars:
      # META (Agente IA WhatsApp)
      - key: META_TOKEN
        value: "EAAQZBWPqKZAhsBACfZCN7c3k4ZBVoEGALrjZATsb0cCZBjlXfJmL0fFQqlZCO4we3btmOkM4ZCAh7sv89F2vnhPZCV7lPZBVh9eVxZBAhKgAFVzYKy8pl1MV2cRga6FnVKxAJp9P9HZCE4dQi8XvwpMZA4OZAg63qUchvbjaHnYZAVj4r5jZCUZCyt6b"
      - key: META_APP_ID
        value: "1058026462824251"
      - key: META_APP_SECRET
        value: "e13e5fa067bca4f186d0a47c5b3de66e"
      - key: META_PHONE_ID
        value: "422524617608742"
      - key: META_VERSION
        value: "v20.0"

      # RESERVO (Agendamiento Body Elite)
      - key: RESERVO_API_KEY
        value: "f0Hq15w0M0nrxU8d7W64x5t2S6L4h9"
      - key: RESERVO_URL
        value: "https://agendamiento.reservo.cl/makereserva/agenda/f0Hq15w0M0nrxU8d7W64x5t2S6L4h9"

      # General
      - key: NODE_ENV
        value: "production"
