services:
  - type: web
    name: zara-bodyelite-1
    env: node
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: PAGE_ACCESS_TOKEN
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
      - key: BUSINESS_ACCOUNT_ID
        sync: false
      - key: PORT
        value: 3000
