services:
- type: web
  name: zara-bodyelite-1
  env: node
  plan: free
  buildCommand: "npm install"
  startCommand: "npm start"
  envVars:
  - key: PAGE_ACCESS_TOKEN
    sync: false
  - key: PHONE_NUMBER_ID
    sync: false
  - key: VERIFY_TOKEN
    sync: false
  - key: PORT
    value: 3000
